// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUavrK6J7ou9Z4uN6d3Tc5d3YdMGRrxds',
    appId: '1:695101733939:web:684010f72b1d5c6b9e7746',
    databaseURL: 'https://test-c1fe6-default-rtdb.firebaseio.com',
    messagingSenderId: '695101733939',
    projectId: 'test-c1fe6',
    authDomain: 'test-c1fe6.firebaseapp.com',
    storageBucket: 'test-c1fe6.appspot.com',
    measurementId: 'G-ZCWBSZ8BE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-6PCjvVqEXdM6oszQh3WnHQsrzE-EMI',
    appId: '1:695101733939:android:74283c716938318c9e7746',
    databaseURL: 'https://test-c1fe6-default-rtdb.firebaseio.com',
    messagingSenderId: '695101733939',
    projectId: 'test-c1fe6',
    storageBucket: 'test-c1fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPP8TeyundshUlzbj0sB1VNGRP7lXesg',
    appId: '1:695101733939:ios:75f62226d6c03d379e7746',
    databaseURL: 'https://test-c1fe6-default-rtdb.firebaseio.com',
    messagingSenderId: '695101733939',
    projectId: 'test-c1fe6',
    storageBucket: 'test-c1fe6.appspot.com',
    iosBundleId: 'com.example.manage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPP8TeyundshUlzbj0sB1VNGRP7lXesg',
    appId: '1:695101733939:ios:ba5ef8026fa2ede39e7746',
    databaseURL: 'https://test-c1fe6-default-rtdb.firebaseio.com',
    messagingSenderId: '695101733939',
    projectId: 'test-c1fe6',
    storageBucket: 'test-c1fe6.appspot.com',
    iosBundleId: 'com.example.manage.RunnerTests',
  );
}
